import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
QUESTIONS_DIR = ROOT / "questions"
OUT_FILE = ROOT / "data" / "questions-data.js"

TYPE_LABELS = {
    "mcq": "MCQ",
    "vsa": "VSA",
    "sa": "SA",
    "la": "LA",
    "ar": "AR",
    "casestudy": "Case Study",
    "categorytest": "Category Test",
    "vsatest/vsa": "VSA Test",
    "vsatest/vsa_adaptive": "VSA Adaptive",
}

TYPE_RANK = {k: i for i, k in enumerate(TYPE_LABELS)}


def chapter_num(name):
    m = re.search(r"(\d+)", name)
    return int(m.group(1)) if m else 999


def type_key(rel):
    return "/".join(rel.split("/"))


def type_label(rel):
    key = type_key(rel)
    if key in TYPE_LABELS:
        return TYPE_LABELS[key]
    return re.sub(r"[_-]+", " ", key).strip().title()


def qtype_label(q, fallback):
    qt = (q.get("question_type") or "").strip().upper()
    if not qt:
        return fallback
    return {
        "MCQ": "MCQ",
        "VSA": "VSA",
        "SA": "SA",
        "SHORT ANSWER": "SA",
        "LA": "LA",
        "LONG ANSWER": "LA",
        "AR": "AR",
        "CASESTUDY": "Case Study",
        "CASE STUDY": "Case Study",
    }.get(qt, qt.title())


def collect_images(q):
    imgs = []
    for key in ("imageurl",):
        v = q.get(key)
        if isinstance(v, str) and v:
            imgs.append(v)
    for key in ("diagram", "explanation_image", "question_image"):
        v = q.get(key)
        if isinstance(v, list):
            for u in v:
                if isinstance(u, str) and u and u not in imgs:
                    imgs.append(u)
    return imgs[:8]


def build_entry(q, subject, chapter, rel):
    fallback = type_label(rel)
    options = q.get("options") or {}
    if isinstance(options, str):
        options = {}
    e = {
        "id": q.get("id") or q.get("_id") or q.get("question_id") or "",
        "subject": subject,
        "chapter": chapter,
        "typeKey": type_key(rel),
        "typeLabel": type_label(rel),
        "qtype": qtype_label(q, fallback),
        "category": (q.get("category") or "") or "",
        "question": str(q.get("question") or ""),
        "options": options,
        "isOptionsImage": bool(q.get("is_options_image")),
        "hasAnswer": bool(q.get("answeroption")),
        "answer": q.get("answeroption") or "",
        "explanation": str(q.get("explanation") or ""),
        "difficulty": (q.get("difficulty") or "") or "",
        "images": collect_images(q),
    }
    return e


def main():
    if not QUESTIONS_DIR.exists():
        sys.exit(f"questions dir not found: {QUESTIONS_DIR}")

    by_id = {}
    seen_files = 0
    counts = {"math": 0, "phy": 0}

    for subject_dir in sorted(d for d in QUESTIONS_DIR.iterdir() if d.is_dir()):
        subject = subject_dir.name.lower()
        for chapter_dir in sorted(d for d in subject_dir.iterdir() if d.is_dir()):
            chapter = chapter_dir.name
            for f in sorted(chapter_dir.rglob("*.json")):
                rel = f.parent.relative_to(chapter_dir).as_posix()
                try:
                    with open(f, "r", encoding="utf-8") as fh:
                        q = json.load(fh)
                except Exception as ex:
                    print(f"    skip {f}: {ex}")
                    continue
                seen_files += 1
                e = build_entry(q, subject, chapter, rel)
                fid = (subject, e["id"])
                prev = by_id.get(fid)
                if prev is None or (e["hasAnswer"] and not prev["hasAnswer"]):
                    by_id[fid] = e
                    counts[subject] += 1
                else:
                    pass

    entries = [e for (_, e) in by_id.items()]
    entries.sort(
        key=lambda e: (
            e["subject"],
            chapter_num(e["chapter"]),
            TYPE_RANK.get(e["typeKey"], 99),
            e["id"],
        )
    )

    payload = json.dumps(entries, ensure_ascii=False, separators=(",", ":"))
    payload = payload.replace("</", "<\\/")
    out = "/* Auto-generated by build_data.py -- do not edit by hand */\n"
    out += "window.QUESTION_DATA = " + payload + ";\n"

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(out, encoding="utf-8")

    print(f"[+] Scanned {seen_files} JSON files")
    print(f"[+] Unique questions: {len(entries)} (math={counts['math']}, phy={counts['phy']})")
    print(f"[+] Annotated (have answer): {sum(1 for e in entries if e['hasAnswer'])}")
    print(f"[+] Wrote {OUT_FILE} ({OUT_FILE.stat().st_size / 1024 / 1024:.1f} MB)")


if __name__ == "__main__":
    main()